Responsive website
tajulafreen/Portfolio pull request #4
Opened 2023-05-10 09:19 UTC by tajulafreen

In this project, I am using HTML and CSS to create a website.
1.✅NO linter errors.
2.✅ documented your work in a professional way.
3.✅ I used the correct GitHub flow

2023-05-10 11:25 UTC, usorfaitheloho requested changes
## Hi @tajulafreen   :clap:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif)

## To Highlight :clap:  
:arrow_forward: Git/Github flow best practices has been followed :heavy_check_mark: 
:arrow_forward: Good code quality :heavy_check_mark: 
:arrow_forward: Good PR title and summary :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 11:25 UTC, usorfaitheloho commented on index.html
> +        <!--------------- Desktop ------------------->
According to the project requirement, you are to ensure that your design is the same as the Figma design given. Your desktop version still has the `hamburger` menu which is meant for mobile only. Please make the `hamburger` invisible for the desktop version only and then make this `desktop nav` you added visible for the desktop only, and kindly make the desktop nav centered 😄 

Your design : 
![image](https://github.com/tajulafreen/Portfolio/assets/20537712/77f96f2a-8793-44a5-9dde-4ea6c47d7590)


Figma design :
![image](https://github.com/tajulafreen/Portfolio/assets/20537712/5c5d5b45-fe65-47ab-87c3-7076653cb1c6)

2023-05-10 11:25 UTC, usorfaitheloho commented on index.html
>          don’t hesitate to contact me.</p></div>
As stated earlier, please you're to follow the design in the Figma template you were given both for your background images and for your text alignment too. All your background images are supposed to be at the edge surrounding your header in a proper and orderly manner while your header is in the center as shown in the Figma design then your social icons should be arranged too. please kindly implement that for your design 😄 

Figma design :
![image](https://github.com/tajulafreen/Portfolio/assets/20537712/2f3a0f6e-b209-4007-a7bf-f77cc56b91e8)



Your design ;
![image](https://github.com/tajulafreen/Portfolio/assets/20537712/772ad5f4-d8e5-4d43-91c8-6ce39d122a5c)

2023-05-10 11:25 UTC, usorfaitheloho commented on responsiveness.css
> +
According to the project requirement, you are to ensure that your design is the same as the Figma design given. Please Your Project section for the desktop version should have  2 rows with 3 projects each (6 projects in total) to give you a better view of what we have in the template also remember to follow all alignments for this section 😄 .

Figma design:

https://github.com/tajulafreen/Portfolio/assets/20537712/35b83063-4487-42fb-a667-cbd68caf92ff



Your design:

https://github.com/tajulafreen/Portfolio/assets/20537712/935a843a-fbb6-4383-a012-7fd63218e594

2023-05-10 11:25 UTC, usorfaitheloho commented on responsiveness.css
> +}
Please as I've suggested previously that you should follow the Figma design for the desktop version as much as possible, please kindly implement it for other aspects of your desktop version which also includes: the `About section` and `Contact section` . part of the problem you have with your code could be that you have several css files with conflicting class properties. You could try to have just one or two maximum css files and ensure that the properties are unique for each class 😄 

Figma design : 

https://github.com/tajulafreen/Portfolio/assets/20537712/2ab407ef-cbdc-4e22-928a-03b1011adecd

Your design :


https://github.com/tajulafreen/Portfolio/assets/20537712/b924d154-9e73-4304-a5c5-2cd3453d67c1

2023-05-11 05:46 UTC, emmiiorji approved these changes
Hi @tajulafreen, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights✔️

- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 05:47 UTC, merged