Portfolio : Popup window
tajulafreen/Portfolio pull request #8
Opened 2023-05-25 03:23 UTC by tajulafreen

In this PR I did the following 👍 :
✅ Add a javascript pop window to the project buttons See Project
✅ Add EventListener to the project buttons See Project
✅ Make the website more dynamic
✔For every single see project button the technologies on project descriptions change.
✔On the pop-up window there are two buttons: See Live and See Source that navigate to the related pages in a new tab.-
✅ No linters error.
✅ Figma [template]

2023-05-25 14:28 UTC, Lizdev-05 requested changes
Hi @tajulafreen, @Ejikeokegbe, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>
## Highlights
- Correct GitHub Flow 👍

- Good commit history 💰

- Good PR title/description 💯

- All linters passed 🏅

- Personalised README file 👍
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Putting the images in a folder so that your file size can be light and minimal

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 14:28 UTC, Lizdev-05 commented on index.html
> +
Since you have dynamically created the project section in JavaScript in line with the project requirement, could you remove it from the HTM file since this will not be useful again? 😊

2023-05-25 14:28 UTC, Lizdev-05 commented on styles.css
> +  }
Great job so far 👍 , I think it will be great if you give the buttons enough padding in line with what we have on the Figma design 

Figma Design :
<img width="346" alt="image" src="https://github.com/tajulafreen/Portfolio/assets/73854999/7bd66fd3-f692-4f15-9b1f-78f24598b031">
Your Design :
<img width="317" alt="image" src="https://github.com/tajulafreen/Portfolio/assets/73854999/5b783947-c697-496f-a6c4-bdb7420ed60e">

2023-05-25 14:28 UTC, Lizdev-05 commented on styles.css
> +
I noticed that there is no picture nor button on the viewport of 768, kindly update it so we can have buttons to check the live and source code on every viewport.
<img width="555" alt="image" src="https://github.com/tajulafreen/Portfolio/assets/73854999/013f5572-dfe1-4b5c-aa01-8be01bf92141">

2023-05-25 17:27 UTC, tajulafreen commented on index.html
> +
Hi @Lizdev-05 ,
I tried to remove that from the HTML file when I removed this it didn't work..

2023-05-26 10:43 UTC, NatiG25 requested changes
## :yellow_circle: CHANGES REQUIRED :yellow_circle: 

## Hi @tajulafreen :wave:, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights
:heavy_check_mark: Great job! Removing unnecessary content from the index.html
:heavy_check_mark: Awesome work! On making sure that the entire popup content is available on every viewport.

![](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 10:43 UTC, NatiG25 commented on styles.css
> +}
- [ ] Kindly, make sure to match the Figma design as much as possible. Currently, your popup buttons are missing enough padding.

<table>
<tr>
<th>Your design</th>
<th>Figma</th>
</tr>
  <tr>
    <td><img src="https://github.com/tajulafreen/Portfolio/assets/86069740/4b22b792-f35e-4c52-9efd-f292ef232205"/></td>
    <td><img src="https://github.com/tajulafreen/Portfolio/assets/86069740/c90c386f-9966-4319-b6cf-8a5544c0229e"/></td>
  </tr>
</table>

2023-05-26 12:02 UTC, cynthiainga approved these changes
## STATUS APPROVED ✔️ 🎉 

Hi @tajulafreen, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] No interest errors ✔️ 
- [ ] Correct GitHub flow ✔️ 

## Optional suggestions

- [OPTIONAL] I noticed that your commit messages are not in the imperative commit message and should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8) 😁 
- [OPTIONAL] Also as mentioned by the previous reviewer it would be better if you create a folder for your images, it would help to be more organized 😁 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 12:03 UTC, merged